CREATE TABLE "GCG_6920_CAL" (
 "L2ID" CHAR(50),
 "CAL_NOTES" NVARCHAR(1000),
 "CAL_LINK_DOC" CHAR(200),
 "DATE_LAST_CAL" DATE,
 "DATE_CAL_DUE" DATE,
 "GS_USER" CHAR(10),
 "MANUF" CHAR(50),
 "MODEL" CHAR(50),
 "SERIAL" CHAR(50),
 "CAL_FREQ" INTEGER );
